// =============================================
//   HINTS DICTIONARY - 8086 Tooltip System
// =============================================

const HINTS = {
  // ---- Registers ----
  "AX": "Accumulator 16-bit. Dùng ngầm định cho MUL, DIV, IN, OUT, INT 21h. Gồm AH (byte cao) và AL (byte thấp).",
  "AH": "Byte cao của AX. Dùng chứa mã chức năng INT 21h (vd: AH=4Ch = thoát, AH=09h = in chuỗi).",
  "AL": "Byte thấp của AX. Dùng ngầm định cho MUL 8-bit, DIV 8-bit, IN/OUT, XLAT, CBW.",
  "BX": "Base Register 16-bit. Thanh ghi duy nhất dùng được trong [BX] để truy cập bộ nhớ (ngoài BP). Dùng cho XLAT.",
  "BH": "Byte cao của BX.",
  "BL": "Byte thấp của BX.",
  "CX": "Counter Register 16-bit. Bộ đếm ngầm định cho LOOP, REP, dịch/quay nhiều bit (CL).",
  "CL": "Byte thấp CX. Dùng đếm số bit dịch/quay: SHL AX, CL.",
  "DX": "Data Register 16-bit. Chứa 16 bit cao khi nhân 16-bit (DX:AX), số dư khi chia 16-bit. Chứa địa chỉ cổng I/O gián tiếp.",
  "DL": "Byte thấp DX. Chứa số dư khi chia 8-bit (DIV BL → AL=thương, AH=dư).",
  "SI": "Source Index 16-bit. Chỉ số nguồn trong lệnh chuỗi (DS:SI). Dùng được trong [SI].",
  "DI": "Destination Index 16-bit. Chỉ số đích trong lệnh chuỗi (ES:DI). Dùng được trong [DI].",
  "SP": "Stack Pointer 16-bit. Trỏ đỉnh stack (SS:SP). PUSH: SP−2. POP: SP+2. KHÔNG dùng được trong [...] trên 8086.",
  "BP": "Base Pointer 16-bit. Truy cập tham số/biến cục bộ trong stack frame. [BP+4]=param1, [BP-2]=local. Ngầm định → SS.",
  "IP": "Instruction Pointer 16-bit. Trỏ lệnh tiếp theo (CS:IP). CPU tự quản lý, không truy cập trực tiếp.",
  "CS": "Code Segment. Chứa địa chỉ đoạn mã. Không thể MOV giá trị trực tiếp vào CS.",
  "DS": "Data Segment. Chứa địa chỉ đoạn dữ liệu. Cần nạp: MOV AX,@DATA / MOV DS,AX.",
  "SS": "Stack Segment. Chứa địa chỉ đoạn ngăn xếp. Dùng tự động với PUSH/POP/CALL/RET.",
  "ES": "Extra Segment. Đoạn phụ, bắt buộc cho lệnh chuỗi đích (ES:DI). Dùng segment override ES:[BX].",
  "FLAGS": "Thanh ghi cờ 16-bit chứa 9 cờ: 6 cờ trạng thái (CF,PF,AF,ZF,SF,OF) + 3 cờ điều khiển (TF,IF,DF).",

  // ---- Flags ----
  "CF": "Carry Flag. =1 nếu có nhớ/mượn ở bit MSB (số không dấu). INC/DEC KHÔNG ảnh hưởng CF!",
  "ZF": "Zero Flag. =1 nếu kết quả phép tính = 0.",
  "SF": "Sign Flag. = bit MSB của kết quả. =1 nếu kết quả âm (số có dấu).",
  "OF": "Overflow Flag. =1 nếu tràn số có dấu: 2 số cùng dấu cộng ra khác dấu.",
  "AF": "Auxiliary Flag. =1 nếu có nhớ từ bit 3 sang bit 4. Dùng cho BCD (DAA, DAS).",
  "PF": "Parity Flag. =1 nếu byte thấp kết quả có số lượng bit 1 chẵn.",
  "DF": "Direction Flag. DF=0 (CLD): SI/DI tăng. DF=1 (STD): SI/DI giảm. Dùng cho lệnh chuỗi.",
  "IF": "Interrupt Flag. IF=1: cho phép ngắt cứng. IF=0: cấm ngắt. STI/CLI.",
  "TF": "Trap Flag. TF=1: chế độ chạy từng bước (single step) để debug.",

  // ---- Instructions ----
  "MOV": "MOV dest, src — Sao chép dữ liệu từ src sang dest. KHÔNG ảnh hưởng cờ.",
  "ADD": "ADD dest, src — dest = dest + src. Cập nhật 6 cờ: CF, PF, AF, ZF, SF, OF.",
  "SUB": "SUB dest, src — dest = dest − src. Cập nhật 6 cờ. CMP giống SUB nhưng không lưu kết quả.",
  "INC": "INC dest — dest = dest + 1. Cập nhật PF, AF, ZF, SF, OF. KHÔNG ảnh hưởng CF!",
  "DEC": "DEC dest — dest = dest − 1. Giống INC, KHÔNG ảnh hưởng CF!",
  "MUL": "MUL src — Nhân không dấu. 8-bit: AX = AL × src. 16-bit: DX:AX = AX × src.",
  "DIV": "DIV src — Chia không dấu. 8-bit: AL = AX ÷ src, AH = dư. 16-bit: AX = DX:AX ÷ src, DX = dư.",
  "IMUL": "IMUL src — Nhân có dấu. Tương tự MUL nhưng cho số signed.",
  "IDIV": "IDIV src — Chia có dấu. Tương tự DIV nhưng cho số signed.",
  "NEG": "NEG dest — Lấy bù 2: dest = 0 − dest. CF=1 trừ khi dest=0. Đặc biệt: NEG 8000h = 8000h, OF=1.",
  "NOT": "NOT dest — Đảo mọi bit (bù 1). KHÔNG ảnh hưởng cờ.",
  "AND": "AND dest, src — dest = dest AND src. Xóa CF và OF. Dùng để mask bit.",
  "OR": "OR dest, src — dest = dest OR src. Xóa CF và OF. Dùng để set bit.",
  "XOR": "XOR dest, src — dest = dest XOR src. Xóa CF, OF. XOR AX,AX → xóa AX nhanh nhất.",
  "TEST": "TEST dest, src — Giống AND nhưng KHÔNG lưu kết quả. Xóa CF, OF. Chỉ cập nhật ZF, SF, PF.",
  "CMP": "CMP dest, src — Giống SUB nhưng KHÔNG lưu kết quả. Cập nhật tất cả 6 cờ. Dùng trước Jcc.",
  "SHL": "SHL dest, count — Dịch trái logic. Bit MSB → CF. Điền 0 vào LSB. SHL AX,1 = nhân 2.",
  "SHR": "SHR dest, count — Dịch phải logic. Bit LSB → CF. Điền 0 vào MSB. Dùng cho số không dấu.",
  "SAR": "SAR dest, count — Dịch phải số học. GIỮ NGUYÊN bit dấu (MSB). Dùng cho số có dấu.",
  "SAL": "SAL dest, count — Dịch trái số học. Giống SHL.",
  "ROL": "ROL dest, count — Quay trái: bit MSB → CF và → LSB. Không mất dữ liệu.",
  "ROR": "ROR dest, count — Quay phải: bit LSB → CF và → MSB.",
  "RCL": "RCL dest, count — Quay trái qua cờ CF. Bit MSB → CF, CF cũ → LSB. Dùng dịch số > 16 bit.",
  "RCR": "RCR dest, count — Quay phải qua cờ CF. Bit LSB → CF, CF cũ → MSB.",
  "PUSH": "PUSH src — SP = SP − 2, rồi [SS:SP] = src. Stack grows down. LIFO.",
  "POP": "POP dest — dest = [SS:SP], rồi SP = SP + 2.",
  "CALL": "CALL target — PUSH IP (hoặc CS:IP nếu FAR), rồi nhảy đến target.",
  "RET": "RET — POP IP (hoặc CS:IP). Quay về sau CALL. RET n: POP IP rồi SP += n.",
  "LOOP": "LOOP label — CX = CX − 1. Nếu CX ≠ 0 → nhảy đến label. KHÔNG kiểm tra cờ.",
  "LOOPE": "LOOPE/LOOPZ — CX−−, nhảy nếu CX≠0 VÀ ZF=1.",
  "LOOPZ": "LOOPZ/LOOPE — CX−−, nhảy nếu CX≠0 VÀ ZF=1.",
  "LOOPNE": "LOOPNE/LOOPNZ — CX−−, nhảy nếu CX≠0 VÀ ZF=0.",
  "JMP": "JMP target — Nhảy không điều kiện đến target.",
  "JE": "JE/JZ — Nhảy nếu ZF=1 (bằng nhau).",
  "JZ": "JZ/JE — Nhảy nếu ZF=1 (kết quả = 0).",
  "JNE": "JNE/JNZ — Nhảy nếu ZF=0 (không bằng).",
  "JNZ": "JNZ/JNE — Nhảy nếu ZF=0.",
  "JG": "JG/JNLE — Nhảy nếu lớn hơn (signed): ZF=0 VÀ SF=OF.",
  "JGE": "JGE/JNL — Nhảy nếu ≥ (signed): SF=OF.",
  "JL": "JL/JNGE — Nhảy nếu nhỏ hơn (signed): SF≠OF.",
  "JLE": "JLE/JNG — Nhảy nếu ≤ (signed): ZF=1 HOẶC SF≠OF.",
  "JNL": "JNL/JGE — Jump if Not Less. Nhảy nếu SF=OF (≥ 0 cho số có dấu).",
  "JA": "JA/JNBE — Nhảy nếu lớn hơn (unsigned): CF=0 VÀ ZF=0.",
  "JAE": "JAE/JNB — Nhảy nếu ≥ (unsigned): CF=0.",
  "JB": "JB/JNAE — Nhảy nếu nhỏ hơn (unsigned): CF=1.",
  "JBE": "JBE/JNA — Nhảy nếu ≤ (unsigned): CF=1 HOẶC ZF=1.",
  "JC": "JC — Nhảy nếu CF=1 (có carry/borrow).",
  "JNC": "JNC — Nhảy nếu CF=0.",
  "JS": "JS — Nhảy nếu SF=1 (kết quả âm).",
  "JNS": "JNS — Nhảy nếu SF=0 (kết quả dương/0).",
  "JO": "JO — Nhảy nếu OF=1 (tràn signed).",
  "INT": "INT n — Gọi ngắt mềm số n. PUSH FLAGS, CS, IP rồi nhảy đến ISR.",
  "IRET": "IRET — Trở về từ ngắt. POP IP, CS, FLAGS.",
  "LEA": "LEA dest, src — Load Effective Address. Chỉ tính địa chỉ, KHÔNG đọc bộ nhớ. LEA BX,[SI+5] → BX = SI+5.",
  "XCHG": "XCHG dest, src — Hoán đổi giá trị 2 toán hạng. KHÔNG ảnh hưởng cờ.",
  "CBW": "CBW — Convert Byte to Word. Mở rộng dấu AL → AX. Nếu AL ≥ 0: AH=00h, nếu AL < 0: AH=FFh.",
  "CWD": "CWD — Convert Word to Doubleword. Mở rộng dấu AX → DX:AX.",
  "MOVSB": "MOVSB — Move String Byte: [ES:DI] ← [DS:SI]. SI±1, DI±1 (tuỳ DF). Dùng với REP.",
  "MOVSW": "MOVSW — Move String Word: [ES:DI] ← [DS:SI]. SI±2, DI±2.",
  "STOSB": "STOSB — Store String Byte: [ES:DI] ← AL. DI±1.",
  "LODSB": "LODSB — Load String Byte: AL ← [DS:SI]. SI±1.",
  "CMPSB": "CMPSB — Compare String Byte: [DS:SI] − [ES:DI], cập nhật cờ. SI±1, DI±1.",
  "SCASB": "SCASB — Scan String Byte: AL − [ES:DI], cập nhật cờ. DI±1.",
  "REP": "REP — Repeat prefix. Lặp lệnh chuỗi tiếp theo CX lần. Mỗi lần CX−−.",
  "REPE": "REPE/REPZ — Lặp khi CX≠0 VÀ ZF=1. Dùng với CMPSB, SCASB.",
  "REPNE": "REPNE/REPNZ — Lặp khi CX≠0 VÀ ZF=0.",
  "CLD": "CLD — Clear Direction Flag. DF=0 → SI/DI tăng (xử lý chuỗi từ thấp→cao).",
  "STD": "STD — Set Direction Flag. DF=1 → SI/DI giảm (xử lý chuỗi từ cao→thấp).",
  "CLI": "CLI — Clear Interrupt Flag. IF=0 → cấm ngắt cứng.",
  "STI": "STI — Set Interrupt Flag. IF=1 → cho phép ngắt cứng.",
  "PUSHF": "PUSHF — PUSH FLAGS register lên stack.",
  "POPF": "POPF — POP đỉnh stack vào FLAGS register.",
  "LAHF": "LAHF — Load AH from Flags. AH ← byte thấp FLAGS (SF,ZF,AF,PF,CF).",
  "SAHF": "SAHF — Store AH into Flags. Byte thấp FLAGS ← AH.",
  "DAA": "DAA — Decimal Adjust after Addition. Điều chỉnh AL về BCD hợp lệ sau ADD.",
  "DAS": "DAS — Decimal Adjust after Subtraction.",
  "AAA": "AAA — ASCII Adjust after Addition.",
  "AAS": "AAS — ASCII Adjust after Subtraction.",
  "XLAT": "XLAT — AL = [DS:BX + AL]. Tra bảng: BX trỏ đầu bảng, AL là index, kết quả ghi đè AL.",
  "XLATB": "XLATB — Giống XLAT. AL = [DS:BX + AL].",
  "HLT": "HLT — Halt. Dừng CPU cho đến khi có ngắt.",
  "NOP": "NOP — No Operation. Không làm gì, tốn 1 chu kỳ. Opcode 90h.",
  "IN": "IN dest, port — Đọc dữ liệu từ cổng I/O. IN AL,port8 hoặc IN AX,DX.",
  "OUT": "OUT port, src — Ghi dữ liệu ra cổng I/O.",

  // ---- Concepts ----
  "BIU": "Bus Interface Unit — đơn vị giao tiếp bus trong 8086. Chứa 4 thanh ghi đoạn, IP, bộ cộng địa chỉ 20-bit, hàng đợi lệnh 6 byte.",
  "EU": "Execution Unit — đơn vị thực thi trong 8086. Chứa ALU, 4 thanh ghi đa năng, SP/BP/SI/DI, FLAGS, bộ giải mã lệnh.",
  "ALU": "Arithmetic Logic Unit — thực hiện các phép tính số học (+,−,×,÷) và logic (AND, OR, XOR, NOT).",
  "CU": "Control Unit — Đơn vị điều khiển: Fetch (nạp lệnh) → Decode (giải mã) → Execute (phát tín hiệu điều khiển).",
  "LIFO": "Last In First Out — Cấu trúc dữ liệu stack: phần tử vào sau ra trước.",
  "little-endian": "Byte thấp lưu ở địa chỉ thấp. VD: AX=1234h lưu tại [addr]=34h, [addr+1]=12h.",
  "Von Neumann": "Kiến trúc dùng chung 1 bus cho dữ liệu và lệnh. Đơn giản nhưng có nghẽn cổ chai (bottleneck).",
  "Harvard": "Kiến trúc dùng bus riêng cho dữ liệu và lệnh. Nhanh hơn, song song được, nhưng phức tạp.",
  "Pipeline": "8086 pipeline sơ khai: BIU nạp trước lệnh trong khi EU thực thi lệnh hiện tại.",
  "Protected Mode": "Chế độ bảo vệ (từ 80286): đoạn bắt đầu tại địa chỉ bất kỳ, độ dài linh hoạt, bảo vệ bộ nhớ, đa nhiệm.",
  "Real Mode": "Chế độ thực (8086): 1MB bộ nhớ, không bảo vệ, đoạn cố định 64KB, PA = Segment×16 + Offset.",
  "Segment Override": "Tiền tố ghi đè đoạn (CS:, DS:, ES:, SS:). Chỉ có hiệu lực cho 1 lệnh ngay sau. Thêm 1 byte, 2 chu kỳ.",
  "Prefetch Queue": "Hàng đợi lệnh nạp trước: 8086 = 6 byte, 8088 = 4 byte. BIU tự nạp khi bus rảnh.",
  "bù 2": "Two's complement — biểu diễn số âm: đảo bit rồi +1. Thuận tiện: dùng cùng mạch cộng cho signed và unsigned.",
  "COM": "Chương trình .COM: CS=DS=SS=ES, tối đa 64KB, bắt đầu tại offset 100h, kết thúc INT 20h.",
  "EXE": "Chương trình .EXE: CS≠DS≠SS, kích thước không giới hạn, kết thúc INT 21h/4Ch.",
  "@DATA": "Ký hiệu assembler chỉ địa chỉ segment của đoạn .DATA. Phải nạp: MOV AX,@DATA / MOV DS,AX.",
  "INT 21h": "DOS Interrupt. AH=01h: đọc ký tự. AH=02h: in ký tự. AH=09h: in chuỗi. AH=4Ch: thoát chương trình.",
  "stack frame": "Khung stack cho CTC: PUSH BP / MOV BP,SP. [BP+4]=param1, [BP+6]=param2, [BP-2]=local var.",
};
